// Full analysis data for P2P EV Charging business idea
export const FULL_ANALYSIS = {
  sections: [
    {
      title: "Evidence of Quantitative Shortfall & Ambitious Targets",
      content: "Ireland has ~135,000 EVs on the road but aims for 1 million by 2030. This is a massive scaling requirement.\n\nPublic Charger Count: As of late 2023/early 2024, Ireland had approximately 1,700 public charge points. The government's strategy targets increasing this to 4,850 within three years (by ~2027). This implies a recognition of severe current deficiency.\n\nDublin's Dominance & Shortfall: While Dublin has the highest concentration of chargers in Ireland, it's highlighted that Dublin has 'more charge points than the combined count in 25 other counties'. However, even within Dublin, there's criticism of insufficiency. A striking example: Tesla installed only 4 Superchargers within the entire city of Dublin (population >1 million), described as 'impractical' and inadequate by residents. One user explicitly states: 'With a population of over one million people, relying on only four superchargers appears inadequate'.\n\nComparison Context: Ireland trails Europe significantly, with its total EV chargers constituting 'less than one percent of the EU total'. The UK (a relevant comparison) had over 80,000 public charge points by May 2025, highlighting Ireland's relative underdevelopment."
    },
    {
      title: "Evidence of Pain Points & User Experience",
      content: "'Perfect Storm' Slumping Sales: New EV registrations in Ireland saw a decrease of 23.6% in 2024 compared to 2023, though showing some recovery later (25.1% increase YoY in early 2025, but from a lower base). Professor Brian Caulfield (TCD) explicitly links this slump to charging infrastructure, calling it a 'perfect storm' alongside pricing issues, and states: 'EVs will have the biggest impact on meeting our targets in transport... We needed sales to be up 25%, so now we are 50% away from where sales need to be this year'. He adds, 'From my perspective we probably had more announcements this year about EV chargers than we have had EV chargers installed by the Government' and reveals his personal experience: 'I just couldn\'t depend on the public charging infrastructure' forcing him to buy a longer-range car. This is direct testimony linking infrastructure pain to market behaviour."
    },
    {
      title: "Urban Dweller Crisis & Cost Pain",
      content: "Urban Dweller Crisis: A core target demographic for the problem is people without home charging. GoPlugable cites research showing '37% of new EV drivers lack access to home chargers due to living in apartments or lacking driveways'. For these users, reliance on the deficient public network is unavoidable.\n\nCost Pain: Public charging is significantly more expensive than home charging. Wattcharger states home charging averages €0.24 per kWh. ESB public charging rates for members are €0.509/kWh (Standard), €0.589/kWh (Fast), €0.617/kWh (High Power). Non-members pay even more: €0.563/kWh, €0.647/kWh, €0.682/kWh respectively. This means public charging costs are over 100% to nearly 157% higher than home charging for the same energy. An EV driver reliant on public slow charging (without home option) reported paying €0.27/kWh with a subscription, still a premium over home rates. This is a substantial recurring financial penalty."
    },
    {
      title: "Availability, Queuing, and Speed Issues",
      content: "Availability, Queuing, and 'Charge Rage': Users report practical difficulties finding available chargers, especially fast ones. One Cork EV owner highlights the lack of designated waiting bays and potential for 'charge rage': 'There are no designated wait bays to facilitate reasonable queuing. While most drivers are reasonable, charge-rage could become a potential issue'. They also criticize misleading site information (showing 4 chargers but only 2 parking spots). The article concludes: 'the availability of an EV charger relying entirely on luck, causing a significant headache for EV owners across Ireland'.\n\nSpeed and Suitability: Many existing public chargers are slow (22kW AC). While suitable for longer stops, they are impractical for quick top-ups. Tesco faced criticism for installing only 22kW chargers across 52 locations: 'The Tesco chargers are consistently busy. A 22 kW charger is a waste of time, and 50 kW is not particularly high power; north of 100 kW should be standard in many areas'. This mismatch causes frustration and inefficiency."
    },
    {
      title: "Systemic & Structural Hurdles",
      content: "Grid Connection Costs: Explicitly identifies 'Grid Connection Costs' as a 'major impediment' to deploying new charging stations, especially in Northern Ireland. High costs deter private investment and limit government initiatives. This isn't just a lack of will; it's a fundamental economic and infrastructural barrier slowing down solutions.\n\nUrban Space Limitations: Notes that finding suitable locations for chargers in dense cities like Dublin is 'increasingly difficult.' EV charging requires longer parking durations than refuelling, demanding more space – a premium in cities. Planning restrictions add further complexity.\n\nGovernment Funding Gaps: Reports 'substantial funds earmarked for travel projects have gone unspent,' suggesting inefficiency or lack of capacity in deploying resources specifically needed for charging infrastructure. The SEAI home charger grant was also reduced from €600 to €300, diminishing support for a key solution pathway (home charging).\n\nEnergy Demand & Grid Capacity: Rising EV ownership strains an 'already strained electricity grid'. Integrating renewables adds complexity. Significant grid upgrades are needed to handle the load, especially with widespread home and public charging."
    }
  ]
};
